ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: gce
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.global-static-ip-name: gitbase-playground-staging
    path: /*
    hosts:
      - gitbase-playground-staging.srcd.run
    tls:
      - secretName: gitbase-playground-staging-srcd-run-tls
        hosts:
          - gitbase-playground-staging.srcd.run
