service:
  type: NodePort
  port: 8080

bblfshdServer:
  image:
    repository: bblfsh/bblfshd
    tag: v2.12.1
    pullPolicy: IfNotPresent
  drivers:
    install: true
    languages:
      python:
        repository: bblfsh/python-driver
        tag: v2.8.3
      cpp:
        repository: bblfsh/cpp-driver
        tag: v1.2.4
      java:
        repository: bblfsh/java-driver
        tag: v2.6.3
      javascript:
        repository: bblfsh/javascript-driver
        tag: v2.7.3
      bash:
        repository: bblfsh/bash-driver
        tag: v2.5.2
      ruby:
        repository: bblfsh/ruby-driver
        tag: v2.9.2
      go:
        repository: bblfsh/go-driver
        tag: v2.5.3
      csharp:
        repository: bblfsh/csharp-driver
        tag: v1.4.3
      php:
        repository: bblfsh/php-driver
        tag: v2.7.4

gitbaseServer:
  # commit defaults to HEAD unless given
  repositories:
    go-git:
      url: https://github.com/src-d/go-git.git
      #commit: v4.4.0
    gitbase:
      url: https://github.com/src-d/gitbase.git
    gitbase-web:
      url: https://github.com/src-d/gitbase-web.git
    bblfshd:
      url: https://github.com/bblfsh/bblfshd.git
    siva-java:
      url: https://github.com/src-d/siva-java.git
  image:
    repository: srcd/gitbase
    tag: v0.19.0
    pullPolicy: IfNotPresent
  squashEnable: "true"
  readonly: "true"

nodeSelector:
  cloud.google.com/gke-nodepool: default-pool

affinity:
   podAntiAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
     - labelSelector:
        matchExpressions:
         - key: app
           operator: In
           values:
        #if the chart name is changed or a nameOverride is used, this value has to be changed to the new name.
           - gitbase-web
       topologyKey: kubernetes.io/hostname
