version: '3.3'

services:
  gitbase-web:
    image: "srcd/gitbase-web"
    ports:
      - "8080:8080"
    environment:
      GITBASEPG_DB_CONNECTION: root@tcp(gitbase:3306)/none?maxAllowedPacket=4194304
      GITBASEPG_BBLFSH_SERVER_URL: bblfsh:9432
    depends_on:
      - gitbase
  gitbase:
    image: "srcd/gitbase:v0.18.0-beta.1"
    environment:
      BBLFSH_ENDPOINT: bblfsh:9432
      GITBASE_UNSTABLE_SQUASH_ENABLE: "true"
    volumes:
      - ${GITBASEPG_REPOS_FOLDER}:/opt/repos
  bblfsh:
    image: "bblfsh/bblfshd:v2.9.2-drivers"
    privileged: true
