# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "gopkg.in/bblfsh/client-go.v2"
    non-go = false

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/pressly/lg"
  version = "1.0.2"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "gopkg.in/bblfsh/sdk.v1"
  version = "1.15.2"

[[constraint]]
  name = "gopkg.in/bblfsh/client-go.v2"
  version = "2.4.2"

[[constraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/src-d/enry.v1"
  version = "1.6.4"
